#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:06:23.373225.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_block_type() works", {

  f <- kwb.rabimo:::get_block_type

  expect_error(
    f()
    # Argument "usage_types" fehlt (ohne Standardwert)
  )

})
