#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:06:25.180269.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("check_data_types() works", {

  f <- kwb.rabimo:::check_data_types

  expect_error(
    f()
    # Argument "types" fehlt (ohne Standardwert)
  )

})
