#
# This file was generated by kwb.test::create_test_files(),
# launched by fdpunt on 2024-05-02 15:50:34.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("pattern_no_roads() works", {

  f <- kwb.rabimo:::pattern_no_roads

  expect_silent(result <- f())

  expect_type(result, "character")
  expect_length(result, 1L)

})
