#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:30.209409.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("calculate_bagrov_table() works", {

  f <- kwb.rabimo:::calculate_bagrov_table

  expect_error(
    f()
    # Argument "n_values" fehlt (ohne Standardwert)
  )

})
