#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.470892.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_rooting_depth() works", {

  f <- kwb.rabimo:::get_rooting_depth

  expect_error(
    f()
    # Argument "land_type" fehlt (ohne Standardwert)
  )

})
