#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:31.790658.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("to_label() works", {

  f <- kwb.rabimo:::to_label

  expect_error(
    f()
    # Argument "key" fehlt (ohne Standardwert)
  )

})
