#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.358453.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_potential_evaporation() works", {

  f <- kwb.rabimo::get_potential_evaporation

  expect_error(
    f()
    # Argument "is_waterbody" fehlt (ohne Standardwert)
  )

})
