#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:26.841162.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_bagrov_parameter_unsealed() works", {

  f <- kwb.rabimo:::get_bagrov_parameter_unsealed

  expect_error(
    f()
    # Argument "g02" fehlt (ohne Standardwert)
  )

})
