#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:26.625072.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("expand_ranges_in_column() works", {

  f <- kwb.rabimo:::expand_ranges_in_column

  expect_error(
    f()
    # Argument "x" fehlt (ohne Standardwert)
  )

})
