#
# This file was generated by kwb.test::create_test_files(), 
# launched by fdpunt on 2024-05-02 15:50:34.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("identify_data_format_or_stop() works", {

  f <- kwb.rabimo:::identify_data_format_or_stop

  expect_error(
    f()
    # Argument "data" fehlt (ohne Standardwert)
  )

})
