#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:31.790658.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("stack() works", {

  f <- kwb.rabimo:::stack

  expect_error(
    f()
    # nicht anwendbare Methode für 'stack' auf Objekt der Klasse "NULL" angewendet
  )

})
