#
# This file was generated by kwb.test::create_test_files(),
# launched by hsonne on 2024-02-16 08:26:26.841162.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("lookup_bagrov_unsealed() works", {

  f <- kwb.rabimo:::lookup_bagrov_unsealed

  expect_error(f())

})
