#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:06:27.372549.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("set_columns_to_zero_where_almost_zero() works", {

  f <- kwb.rabimo:::set_columns_to_zero_where_almost_zero

  expect_error(
    f()
    # Argument "data" fehlt (ohne Standardwert)
  )

})
