#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-19 13:48:30.244669.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("prepare_config() works", {

  f <- kwb.rabimo:::prepare_config

  expect_error(
    f()
    # Argument "config" fehlt (ohne Standardwert)
  )

})
