#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:26.625072.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("abimo_config_to_config() works", {

  f <- kwb.rabimo::abimo_config_to_config

  expect_error(
    f()
    # Argument "abimo_config" fehlt (ohne Standardwert)
  )

})
