#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:31.83242.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("run_rabimo() works", {

  f <- kwb.rabimo::run_rabimo

  expect_error(
    f()
    # Argument "input" fehlt (ohne Standardwert)
  )

})
