#
# This file was generated by kwb.test::create_test_files(), 
# launched by fdpunt on 2024-05-02 15:50:34.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("veg_class_to_k_index() works", {

  f <- kwb.rabimo:::veg_class_to_k_index

  expect_error(
    f()
    # Argument "veg_class" fehlt (ohne Standardwert)
  )

})
