#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:32.982136.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("list_to_data_frame_with_keys() works", {

  f <- kwb.rabimo::list_to_data_frame_with_keys

  expect_error(
    f()
    # Argument "x" fehlt (ohne Standardwert)
  )

})
