#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:06:27.372549.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("in_range() works", {

  f <- kwb.rabimo:::in_range

  expect_error(
    f()
    # Argument "x" fehlt (ohne Standardwert)
  )

})
