#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.470892.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("estimate_water_holding_capacity() works", {

  f <- kwb.rabimo:::estimate_water_holding_capacity

  expect_error(
    f()
    # Argument "f30" fehlt (ohne Standardwert)
  )

})
