#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:06:27.372549.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("check_column() works", {

  f <- kwb.rabimo:::check_column

  expect_error(
    f()
    # Argument "check" fehlt (ohne Standardwert)
  )

})
