#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:30.145374.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("calculate_main_fraction_sealed() works", {

  f <- kwb.rabimo:::calculate_main_fraction_sealed

  expect_error(
    f()
    # Argument "roof" fehlt (ohne Standardwert)
  )

})
