#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:06:24.082509.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("stop_on_invalid_config() works", {

  f <- kwb.rabimo:::stop_on_invalid_config

  expect_error(
    f()
    # Argument "config" fehlt (ohne Standardwert)
  )

})
