#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-19 13:48:30.274323.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("stop_on_invalid_input() works", {

  f <- kwb.rabimo:::stop_on_invalid_input

  expect_error(
    f()
    # Argument "input" fehlt (ohne Standardwert)
  )

})
