#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:33.013238.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("yearly_height_to_volume_flow() works", {

  f <- kwb.rabimo::yearly_height_to_volume_flow

  expect_error(
    f()
    # Argument "height" fehlt (ohne Standardwert)
  )

})
