#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:32.81272.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("usage_is_horticultural() works", {

  f <- kwb.rabimo:::usage_is_horticultural

  expect_error(
    f()
    # Argument "x" fehlt (ohne Standardwert)
  )

})
