#
# This file was generated by kwb.test::create_test_files(), 
# launched by fdpunt on 2024-05-02 15:50:34.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("matching_names() works", {

  f <- kwb.rabimo:::matching_names

  expect_error(
    f()
    # Argument "pattern" fehlt (ohne Standardwert)
  )

})
