#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.336686.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_climate() works", {

  f <- kwb.rabimo:::get_climate

  expect_error(
    f()
    # Argument "input" fehlt (ohne Standardwert)
  )

})
