#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.31332.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("create_fraction_accessor() works", {

  f <- kwb.rabimo:::create_fraction_accessor

  f()

})
