#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:30.104279.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("prepare_berlin_data() works", {

  f <- kwb.rabimo::prepare_berlin_data

  expect_error(
    f()
    # Argument "data_file" fehlt (ohne Standardwert)
  )

})
