#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-03-07 19:45:51.644057.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("land_type_is_urban() works", {

  f <- kwb.rabimo:::land_type_is_urban

  expect_error(
    f()
    # Argument "x" fehlt (ohne Standardwert)
  )

})
