#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:30.209409.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("real_evapo_transpiration() works", {

  f <- kwb.rabimo::real_evapo_transpiration

  expect_error(
    f()
    # Argument "precipitation" fehlt (ohne Standardwert)
  )

})
