#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-16 14:30:17.486343.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("calculate_delta_W_2() works", {

  f <- kwb.rabimo:::calculate_delta_W_2

  expect_error(
    f()
    # Argument "natural" fehlt (ohne Standardwert)
  )

})
