#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:32.982136.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("expand_to_matrix() works", {

  f <- kwb.rabimo:::expand_to_matrix

  expect_error(
    f()
    # Either nrow or ncol must be given but not both at the same time.
  )

})
