#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.493778.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("get_usage_tuple() works", {

  f <- kwb.rabimo::get_usage_tuple

  expect_error(
    f()
    # Argument "usage" fehlt (ohne Standardwert)
  )

})
