#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:28.530485.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("plot_block_2() works", {

  f <- kwb.rabimo::plot_block_2

  expect_error(
    f()
    # Argument "block" fehlt (ohne Standardwert)
  )

})
