#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:32.982136.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("prefix_names() works", {

  f <- kwb.rabimo:::prefix_names

  expect_error(
    f()
    # Argument "prefix" fehlt (ohne Standardwert)
  )

})
