#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:31.790658.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("c.rects() works", {

  f <- kwb.rabimo:::c.rects

  f()

})
