#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:34.892877.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("second_approximation() works", {

  f <- kwb.rabimo:::second_approximation

  expect_error(
    f()
    # Argument "bag" fehlt (ohne Standardwert)
  )

})
