#
# This file was generated by kwb.test::create_test_files(), 
# launched by fdpunt on 2024-05-02 15:50:34.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("generate_rabimo_area() works", {

  f <- kwb.rabimo::generate_rabimo_area

  expect_error(
    f()
    # Argument "code" fehlt (ohne Standardwert)
  )

})
