#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:26.841162.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("irrigation_in_dry_summer_correction_factor() works", {

  f <- kwb.rabimo:::irrigation_in_dry_summer_correction_factor

  expect_error(
    f()
    # Argument "irrigation" fehlt (ohne Standardwert)
  )

})
