#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-02-16 08:26:32.982136.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("split_into_identical_rows() works", {

  f <- kwb.rabimo:::split_into_identical_rows

  expect_error(
    f()
    # Argument "data" fehlt (ohne Standardwert)
  )

})
